[package]
name = "ts3status"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.3"
log = "0.4.14"
pretty_env_logger = "0.4.0"
serde = "1.0.136"
ts3-query = "0.3.2"
